### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Cloverdfn** [pschmitt/docker-picamera#1]
https://github.com/pschmitt/docker-picamera/blob/f009d84c7938b057fe39eacc25ff96936c3b9fcc/web_streaming.py#L124

Hello, your code has benefited me greatly.But, I have some questions, I hope you can guide me.
Can you add the ability to record video and save it here?

**Comment by pschmitt** [comment]
Glad my container has been useful. What you are asking though is out of scope, docker-picamera's purpose is to broadcast the Raspberry Pi camera's image - nothing more. You should check out the upstream documentation: https://picamera.readthedocs.io.

There is a relevant snippet: https://picamera.readthedocs.io/en/release-1.13/recipes1.html#recording-video-to-a-file
