### ISSUE TITLE
Regarding Capturing Image

### ISSUE THREAD

**Issue by prasanthvajja** [pschmitt/docker-picamera#2]
hi, 
     I am working on the raspberry pi camera. I had done on video streaming with your source code, I want a suggestion or source code to capture a image when i click the html button and if i click the button it should hit the function where i written the code for capturing image. 

Thank you,
prasanth vajja

**Comment by pschmitt** [comment]
I'm afraid that's out of scope. Please refer to [picamera's documentation](https://picamera.readthedocs.io/en/release-1.13/)
